stages:
  - stage: test
    jobs:
      - job: test
        steps:
          - task: DotNetCoreCLI@2   
            displayName: 'Run Tests'
            inputs:
              command: test
              projects: '**/*Tests/*.csproj'
              arguments: '--configuration $(buildConfiguration)'